"""The review pipeline: from a webhook event to comments on the pull request.

Steps, in order:
  1. read the files the pull request changed
  2. fetch the full source of the Python files, which the AST rules need
  3. run the static rules
  4. ask the model for the findings rules cannot express
  5. merge, deduplicate, cap, and post one review
"""

from __future__ import annotations

import logging

from app.ai.providers import LLMProvider
from app.ai.reviewer import review_with_ai
from app.analysis.diff import ChangedFile
from app.analysis.static import deduplicate, run_static_analysis, sort_comments
from app.config import settings
from app.github.client import GitHubClient
from app.models.events import PullRequestEvent
from app.models.review import ReviewComment, ReviewResult
from app.queue.jobs import ReviewJob

logger = logging.getLogger(__name__)

# Fetching whole files costs an API call each, so only do it where it pays off.
AST_EXTENSIONS = (".py",)


async def fetch_sources(
    client: GitHubClient, event: PullRequestEvent, files: list[ChangedFile]
) -> dict[str, str]:
    """Download the full text of the files the AST rules can analyse."""
    sources: dict[str, str] = {}

    for changed_file in files:
        if changed_file.is_deleted or not changed_file.path.endswith(AST_EXTENSIONS):
            continue

        content = await client.get_file_content(
            event.owner, event.repo, changed_file.path, event.head_sha
        )

        if content is not None:
            sources[changed_file.path] = content

    return sources


def to_github_comments(comments: list[ReviewComment]) -> list[dict]:
    """Convert findings into the payload GitHub expects for inline comments.

    Findings with no line number cannot be anchored, so they are left out here
    and appear in the review body instead.
    """
    return [
        {
            "path": comment.path,
            "line": comment.line,
            "side": "RIGHT",
            "body": comment.render(),
        }
        for comment in comments
        if comment.line is not None
    ]


def render_summary(result: ReviewResult, unanchored: list[ReviewComment]) -> str:
    """Build the markdown body of the review.

    It carries the counts, the model summary, and any finding that could not be
    attached to a line, so nothing the review produced gets silently dropped.
    """
    counts = result.counts
    lines = ["## Automated code review", ""]

    if result.summary:
        lines += [result.summary, ""]

    if not result.comments:
        lines += ["No issues found in the changed lines.", ""]
    else:
        lines += [
            f"Reviewed **{result.files_reviewed}** changed file(s) and found "
            f"**{len(result.comments)}** item(s): "
            f"{counts['error']} error, {counts['warning']} warning, {counts['info']} info.",
            "",
        ]

    if unanchored:
        lines += ["### Findings not tied to a changed line", ""]
        for comment in unanchored:
            lines.append(f"- `{comment.path}` - {comment.render()}")
        lines.append("")

    engine = "static analysis + AI" if result.ai_used else "static analysis"
    lines.append(f"<sub>Generated by the Automated Code Review Assistant ({engine}).</sub>")

    return "\n".join(lines)


def cap_comments(comments: list[ReviewComment], limit: int) -> list[ReviewComment]:
    """Keep the most serious findings when there are more than the limit.

    Fifty comments on one pull request get ignored wholesale. The list is
    already sorted worst-first, so cutting the tail keeps what matters.
    """
    return comments[:limit]


async def review_pull_request(
    event: PullRequestEvent,
    client: GitHubClient,
    provider: LLMProvider | None = None,
) -> ReviewResult:
    """Run the whole review for one pull request and post the result."""
    result = ReviewResult(owner=event.owner, repo=event.repo, pr_number=event.pr_number)

    files = await client.list_pull_request_files(event.owner, event.repo, event.pr_number)
    result.files_reviewed = len(files)

    if not files:
        logger.info("No files to review in %s#%s", event.full_name, event.pr_number)
        return result

    sources = await fetch_sources(client, event, files)
    static_comments = run_static_analysis(files, sources)

    ai_comments, ai_summary = await review_with_ai(event.title, files, provider=provider)

    result.ai_used = bool(ai_comments or ai_summary)
    result.summary = ai_summary
    result.comments = cap_comments(
        sort_comments(deduplicate(static_comments + ai_comments)),
        settings.max_comments_per_review,
    )

    anchored = [c for c in result.comments if c.line is not None]
    unanchored = [c for c in result.comments if c.line is None]
    body = render_summary(result, unanchored)

    if not settings.post_comments:
        logger.info("POST_COMMENTS is off. Review for %s not posted.", event.full_name)
        return result

    await client.create_review(
        event.owner,
        event.repo,
        event.pr_number,
        body=body,
        comments=to_github_comments(anchored),
        commit_sha=event.head_sha,
    )
    result.posted = True

    logger.info(
        "Posted review on %s#%s with %d comment(s)",
        event.full_name,
        event.pr_number,
        len(result.comments),
    )
    return result


async def handle_review_job(job: ReviewJob) -> ReviewResult:
    """Queue entry point: authenticate for the installation, then review.

    Exceptions propagate on purpose. The queue catches them, counts the attempt,
    and retries with backoff.
    """
    event = job.event

    if event.installation_id is None:
        raise ValueError(
            f"Event for {job.description} has no installation id, so the app cannot authenticate."
        )

    client = await GitHubClient.for_installation(event.installation_id)

    try:
        return await review_pull_request(event, client)
    finally:
        await client.aclose()
